# Generated by Django 3.2 on 2022-03-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_owner_role', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklanguage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
