# Generated by Django 3.2 on 2022-03-15 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sample_Paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_Name', models.CharField(max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_Password', models.CharField(max_length=255)),
                ('company_state', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntervieweeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.CharField(blank=True, default='', max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('cv', models.FileField(upload_to='')),
                ('interviewed_on', models.DateField(auto_now_add=True)),
                ('language', models.CharField(default='', max_length=255)),
                ('level', models.CharField(default='', max_length=255)),
                ('interviwee_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='IntervieweeTestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed_by_computer', models.BooleanField(default=False)),
                ('remarks', models.TextField(default='')),
                ('interviewee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company_role.intervieweedetail')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sample_Paper.samplepaper')),
            ],
        ),
    ]
