# Generated by Django 3.2 on 2022-03-15 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_role', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sample_Paper', '0001_initial'),
        ('Product_owner_role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_record',
            name='interviewee_TestDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_role.intervieweetestdetails'),
        ),
        migrations.AddField(
            model_name='test_record',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample_Paper.question'),
        ),
        migrations.AddField(
            model_name='test_record',
            name='sample_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample_Paper.samplepaper'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_owner_role.tasklanguage'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_owner_role.tasklevel'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='Sample_Paper.Question'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product_owner_role.tasklanguage'),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product_owner_role.tasklevel'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
