# Generated by Django 3.2 on 2022-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample_Paper', '0005_auto_20220316_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplepaper',
            name='question',
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samplepaper',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
