# Generated by Django 3.2 on 2022-03-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_owner_role', '0003_alter_tasklanguage_logo'),
        ('Sample_Paper', '0006_auto_20220316_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product_owner_role.tasklanguage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product_owner_role.tasklevel'),
        ),
        migrations.AlterField(
            model_name='samplepaper',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_owner_role.tasklanguage'),
        ),
        migrations.AlterField(
            model_name='samplepaper',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product_owner_role.tasklevel'),
        ),
        migrations.RemoveField(
            model_name='samplepaper',
            name='question',
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='question',
            field=models.ManyToManyField(to='Sample_Paper.Question'),
        ),
        migrations.AlterField(
            model_name='samplepaper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
