# Generated by Django 3.2 on 2022-03-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample_Paper', '0009_auto_20220316_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='ques_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample_Paper.question_type'),
        ),
        migrations.AddField(
            model_name='samplepaper',
            name='ques_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sample_Paper.question_type'),
        ),
    ]
